name: Cairo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Scarb
        uses: software-mansion/setup-scarb@v1

      - name: Verify Scarb installation
        run: scarb --version

      - name: Build Cairo contracts
        run: scarb build

      - name: Run tests
        run: scarb test
